pipeline{
    agent any
    environment {
        PATH = "$PATH:/usr/share/maven/bin"
    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/saikrishna-M-8520/DevOps.git'
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
      stage('SonarQube analysis') {
         environment {
         MAVEN_OPTS = "--add-opens=java.base/java.lang=ALL-UNNAMED"
         }
          steps {
             withSonarQubeEnv('sonarqube-8.3') {
               sh "mvn clean package sonar:sonar"
        }
    }
}
        stage('Upload jar To Nexus'){
            steps{
                script{
                    nexusArtifactUploader artifacts: [
                        [
                            artifactId: 'my-java17-app', 
                            classifier: '', 
                            file: "target/my-java17-app-1.0-SNAPSHOT.jar", 
                            type: 'jar'
                        ]
                    ], 
                    credentialsId: 'nexus3', 
                    groupId: 'com.example', 
                    nexusUrl: '13.232.148.227:8081', 
                    nexusVersion: 'nexus3', 
                    protocol: 'http', 
                    repository: 'check-repo',
                    version: '1'
                }
            }
        }        
       
    }
}
